### ISSUE TITLE
Unable to test on Human3.6M using pretrained model

### ISSUE THREAD

**Issue by yerzhan7orazayev** [fabro66/GAST-Net-3DPoseEstimation#11]
Hello there,

I am getting the following error when I try to test on Human3.6M using pretrained model. Namely, I am getting the following error. Could you please suggest a solution? Thanks for your work.
```
python3 trainval.py -k cpn_ft_h36m_dbb -arc 3,3,3 -c checkpoint --evaluate 27_frame_model.bin

Namespace(actions='*', architecture='3,3,3', batch_size=128, bone_length_term=True, by_subject=False, causal=False, channels=128, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='h36m', disable_optimizations=False, downsample=5, dropout=0.05, epochs=60, evaluate='27_frame_model.bin', export_training_curves=False, keypoints='cpn_ft_h36m_dbb', learning_rate=0.001, lr_decay=0.95, no_eval=False, render=False, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subset=1, test_time_augmentation=True, viz_action=None, viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export=None, viz_limit=-1, viz_no_ground_truth=False, viz_output=None, viz_size=5, viz_skip=0, viz_subject=None, viz_video=None)
Loading dataset...
cpn_ft_h36m_dbb
Preparing data...
Loading 2D detections...
/home/orazayy/GAST-Net-3DPoseEstimation/model/local_attention.py:25: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  self.e = nn.Parameter(torch.zeros(out_features, len(self.m[0].nonzero()), dtype=torch.float))
INFO: Receptive field: 27 frames
INFO: Trainable parameter count:  6915984
Loading checkpoint checkpoint/27_frame_model.bin
Traceback (most recent call last):
  File "trainval.py", line 55, in <module>
    model_pos_train, model_pos, checkpoint = load_weight(args, model_pos_train, model_pos)
  File "/home/orazayy/GAST-Net-3DPoseEstimation/main.py", line 224, in load_weight
    print("This model was trained for {} epochs".format(checkpoint["epoch"]))
KeyError: 'epoch'
```

**Comment by fabro66** [comment]
Hi~  You can run it by commenting out this code because there is no epoch information in the pretrained model we provide.

**Comment by yerzhan7orazayev** [comment]
What is your CUDA version? I am getting the following error when using gtx1080ti. 
```
Evaluating...
Traceback (most recent call last):
  File "trainval.py", line 318, in <module>
    run_evaluation(all_actions, action_filter)
  File "trainval.py", line 310, in run_evaluation
    e1, e2 = evaluate(gen, model_pos, joints_left, joints_right, action_key)
  File "/home/orazayy/GAST-Net-3DPoseEstimation/main.py", line 341, in evaluate
    predicted_3d_pos = model_pos(inputs_2d)
  File "/home/orazayy/.conda/envs/wudu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/orazayy/GAST-Net-3DPoseEstimation/model/gast_net.py", line 99, in forward
    x = self._forward_blocks(x)
  File "/home/orazayy/GAST-Net-3DPoseEstimation/model/gast_net.py", line 165, in _forward_blocks
    x = self.relu(self.expand_bn(self.expand_conv(x)))
  File "/home/orazayy/.conda/envs/wudu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/orazayy/.conda/envs/wudu/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/orazayy/.conda/envs/wudu/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

**Comment by yerzhan7orazayev** [comment]
I have a question about the work itself. 

1. Are you using single camera view? 
2. I believe that the input to the model is 2D poses according to your paper, am I correct? 
3. Also, how to obtain 3D poses when running the evaluation mode/or save it somewhere on storage during the evaluation?

Thanks.

**Comment by yerzhan7orazayev** [comment]
Also, I wish to run the code chunk by chunk in jupyter notebook. Namely, 
`python3 trainval.py -k cpn_ft_h36m_dbb -arc 3,3,3 -c checkpoint --evaluate 27_frame_model.bin`. How to pass this arguments in jupyter notebook to `args = parse_args()` so that I can continue running the code?

**Comment by fabro66** [comment]
Hi~   Thank you for your interest in our works. The answers below correspond to your question one by one

1. Yes, our method uses a single camera view.
2. The coordinates in the ".\data\keypoints\baseball.json" we provided are the coordinates of 2D keypoints in RGB images.  The coordinates of keypoints are estimated by 2D pose estimation algorithms (HRNet), which outputs are float coordinates. If you want to draw it by OpenCV, you should convert it to the integer type.
3. We have provided a tutorial on how to generate 3D coordinates on custom videos. Please see "INFERENCE_EN.md" for more details.
4. The size of the receptive field will affect the performance. The larger the receptive field, the better the performance, but it also increases inference time.
5.  In theory, a more powerful GPU will have a faster inference speed. Next, we will do a test on Titan RTX.
