### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/orazayy/GAST-Net-3DPoseEstimation-inference/lib/detector/yolov3/../../../checkpoint/yolov3/yolov3.weights'

### ISSUE THREAD

**Issue by yerzhan7orazayev** [fabro66/GAST-Net-3DPoseEstimation#14]
Dear @fabro66 
I think there is inconsistency in file locations, hence I am getting the following error:

```
python gen_skes.py -v baseball.mp4 -np 1
Loading YOLOv3 network.....
Traceback (most recent call last):
  File "gen_skes.py", line 179, in <module>
    generate_skeletons(video=video_path, output_animation=args.animation, num_person=args.num_person)
  File "gen_skes.py", line 114, in generate_skeletons
    keypoints, scores = hrnet_pose(video, det_dim=416, num_peroson=num_person, gen_output=True)
  File "/home/orazayy/GAST-Net-3DPoseEstimation-inference/lib/pose/hrnet/pose_estimation/gen_kpts.py", line 185, in gen_video_kpts
    human_model = yolo_model(inp_dim=det_dim)
  File "/home/orazayy/GAST-Net-3DPoseEstimation-inference/lib/detector/yolov3/human_detector.py", line 88, in load_model
    model.load_weights(args.weight_file)
  File "/home/orazayy/GAST-Net-3DPoseEstimation-inference/lib/detector/yolov3/darknet.py", line 352, in load_weights
    fp = open(weightfile, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/orazayy/GAST-Net-3DPoseEstimation-inference/lib/detector/yolov3/../../../checkpoint/yolov3/yolov3.weights'
```

Thanks.

**Comment by fabro66** [comment]
Hi~   I just fixed it. You can change the file name of "checkpoints" to "checkpoint"

**Comment by yerzhan7orazayev** [comment]
Thanks, it works now.
