### ISSUE TITLE
Output is not saved (no such file or directory)

### ISSUE THREAD

**Issue by mamdouh97** [fabro66/GAST-Net-3DPoseEstimation#29]
Hi! 
I am trying to recreate the output for the video baseball.mp4. I am getting this error: 

GAST-Net successfully loaded
Generating 3D human pose ...
Saving 3D reconstruction...
Traceback (most recent call last):
  File "gen_skes.py", line 180, in <module>
    generate_skeletons(video=video_path, output_animation=args.animation, num_person=args.num_person)
  File "gen_skes.py", line 159, in generate_skeletons
    np.savez_compressed(output_root+output_npz, reconstruction=prediction)
  File "<__array_function__ internals>", line 6, in savez_compressed
  File "C:\Users\mamdo\anaconda3\envs\gast\lib\site-packages\numpy\lib\npyio.py", line 686, in savez_compressed
    _savez(file, args, kwds, True)
  File "C:\Users\mamdo\anaconda3\envs\gast\lib\site-packages\numpy\lib\npyio.py", line 712, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "C:\Users\mamdo\anaconda3\envs\gast\lib\site-packages\numpy\lib\npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "C:\Users\mamdo\anaconda3\envs\gast\lib\zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\new GAST-NET\\GAST-Net-3DPoseEstimation\\output/output/baseball.npz'

**Comment by lulindeng** [comment]
Hi,

I also get this error before. The code cannot find the directory:  'D:\new GAST-NET\GAST-Net-3DPoseEstimation\output/output/baseball.npz'. 

You can simply change 'np.savez_compressed(output_root+output_npz, reconstruction=prediction)' as 'np.savez_compressed(output_npz, reconstruction=prediction)'.

**Comment by mamdouh97** [comment]
It worked! Thank you.
