### ISSUE TITLE
Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

### ISSUE THREAD

**Issue by PJJie** [fabro66/GAST-Net-3DPoseEstimation#51]
https://github.com/fabro66/GAST-Net-3DPoseEstimation/blob/master/INFERENCE_EN.md

The following problems occurred after the configuration was run

Traceback (most recent call last):
  File "gen_skes.py", line 180, in <module>
    generate_skeletons(video=video_path, output_animation=args.animation, num_person=args.num_person)
  File "gen_skes.py", line 155, in generate_skeletons
    viz_output, input_video_path=video, viewport=(width, height), com_reconstrcution=same_coord)
  File "/home/junjie/tmp/GAST-Net2/tools/vis_h36m.py", line 111, in render_animation
    ax.set_aspect('equal')
  File "/home/共享文件/anaconda3/envs/pytorch13_py37/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

**Comment by vicentowang** [comment]
@PJJie  passe 'auto' instead of 'equal' , solved.

**Comment by MarcvdSluys** [comment]
I tried that, but my sphere looks like a sphere with 'equal' (left) and like an ellipsoid with 'auto' (right).  How can I tell 'auto' to use equal scaling for the x, y and z axes?

![spheres](https://user-images.githubusercontent.com/15965125/163569790-ff79009f-fe78-488e-8b17-ce51220bc88d.png)

Ah, replacing `ax.set_aspect('equal')` with `ax.set_box_aspect([1,1,1])` [solves this](https://stackoverflow.com/a/63625222/1386750).
